### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by kevaundray** [crate-crypto/rust-verkle#21]
Currently, the code is at best research quality.

Once the IPA has been merged, all of it will be refactored to be specific for the ETH use case. If possible without much performance degradation, over a generic width, however these are quite troublesome and a fixed width leads to cleaner code.

**Comment by kevaundray** [comment]
The code has undergone a re-write, however one should note that there are still some parts which need to be cleaned up. I will leave this issue open to track

**Comment by muddlebee** [comment]
@kevaundray I am new to Ethereum community and Rust :) Looking forward to participate in Ethereum Apprenticeship program. Can I work on this project for the Apprenticeship program ?

**Comment by kevaundray** [comment]
Hey, 

Everything is open source so you can work on whatever you want :) 

I don't have the time at the moment to teach Rust or how verkle tries work, so it might be helpful to go through the relevant rust book at the minimum so you are familiar and comfortable. 

For verkle tries, there is some documentation on it from the EIP and on dankradfeist.de, you can also look at the Python and Golang implementations if Rust's syntax seems foreign while learning about verkle tries. There is also a verkle trie channel in the eth R&D discord, if you have questions
