### ISSUE TITLE
Error verifying a block with a single missing slot

### ISSUE THREAD

**Issue by gballet** [crate-crypto/rust-verkle#53]
A test run of the latest branch has produced the following proof:

`00000000020000000a0a05000000538d6beebb32756be0b22c51ae45a9ed96f0299a2fd01f9ef6887946c26fffd25ce9c5ef692a444a65a087ce1cb90a59599bd1249c1fd787eb56787949a8f1e837a9007019834bef8e2c9e2ae868e33370b5a6723bab8a571d0da40046da856f6b90812ef10962d894a520a03813da890084b726e7396b585645ace2dc6c00d75a1fe87728a033caa1184f1349f1a1e70909d9eef21f470499f62f0ebbe387972ff2c70d324e1038f8f1114cd16839c864b8275f684839b90505f04c47875e030998a9eb0ca0419b918a372deeb31fc2b516319705527008f42a81afa21779f2047f388b70fd0e7573b092733bb9a438bb7636bbebcc8036fc2adba4c64acee25da097d74048cb5640f890a6d7ab823af9f181aef6a2d2d08811f1cec209ca4908dcaccb7b429eaf65ae41b5bb949adf038faa2fd391de7afdef986a9d13f5b21f0d2b472cdd14e0e082b5fc413ec6d9e857146883e98f2606641b78788f295424426a6813f6ceec2d741104aca5955005bab47948001fba26d6eee66cb1c89235dd504e3a8b70e21732657fee59aa7a239c25723e5732f44e779a244c2264d973559b6472a4adb461d476636561bd7a40e922af445ae800736f150f21b4adae627a0149d2740f318f2fa8ff7cba047d21fb5c486d9d03b4d55b5439de1f0f3821597a0b55df1848c880a001b66628ad11dd21ac30dfb9d6f6b112dd796415a307ce68a2f3adb6dc7c61c98febe9ad213d4d5dfe3ae52ac11d854cd055d992be0ba6e062e08d0e7e0b2fa59a2e28d504479585ca344be49e250526abf9827e3a5a97ca0df8efaf267e67aff682dfd47bf799d40e560dc7b3c6f2bd9548c5403e26cfb99557eb2ed741d8615db898cdf0a35216caf9dc4e789721bff60b43f13a4a2a26d7fb26f384f405818b37d0cbc7b7a6bec97d5a5be7442edb688af42fe30487bc85e5236f4deff81ada20bc092ae5ddf555691e17742989d34ad0939c29237bc3e6e5d95cdd5b38d1fe6c2758a799cd683ce3756107e3569788d695a909,`

Using my `rust-verkle`-based tool to verify it produces the following output.

```
> cargo run -- -f ~/Downloads/block_14.rlp -p 36ec9df63867e06e1f46b0b4e28c8f7aeca256c53ab3bda067da9c02db388f15
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/verkle-block-sample -f /home/gballet/Downloads/block_14.rlp -p 36ec9df63867e06e1f46b0b4e28c8f7aeca256c53ab3bda067da9c02db388f15`
de-serialized block:
- parent hash: 95b6b3cd2c6a21ac21cc031bde5ff2a56d0471b773cf3044442d88195a8e0bc6
- storage root: 620e50aebae6d4f4aaf81fafe056a2ceb74a6472aba092dea16c182d8fac3fcc
- block number: 0e
- key, value list:
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352600 => 0000000000000000000000000000000000000000000000000000000000000000
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352601 => 0000000000000000000000000000000000000000000000000000000000000000
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352602 => 0100000000000000000000000000000000000000000000000000000000000000
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352603 => f8811a5ee0d54eca4880eaee7b102eae4b3963ff343f50a024c0fd3d367cb8cc
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352604 => 5001000000000000000000000000000000000000000000000000000000000000
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352640 is absent
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352680 => 00608060405234801561001057600080fd5b50600436106100365760003560e0
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352681 => 001c80632e64cec11461003b5780636057361d14610059575b600080fd5b6100
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352682 => 0143610075565b60405161005091906100d9565b60405180910390f35b610073
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352683 => 00600480360381019061006e919061009d565b61007e565b005b600080549050
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352684 => 0090565b8060008190555050565b60008135905061009781610103565b929150
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352685 => 0050565b6000602082840312156100b3576100b26100fe565b5b60006100c184
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352686 => 00828501610088565b91505092915050565b6100d3816100f4565b8252505056
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352687 => 005b60006020820190506100ee60008301846100ca565b92915050565b600081
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352688 => 009050919050565b600080fd5b61010c816100f4565b811461011757600080fd
	744f493648c83c5ede1726a0cfbe36d3830fd5b64a820b79ca77fe1593352689 => 005b5056fea2646970667358221220404e37f487a89a932dca5e77faaf6ca2de
	9661ae0db10ecdb9bea3ef0c5fb46bb233cb6ed7404b77e7b0732512ecc60100 => 0000000000000000000000000000000000000000000000000000000000000000
	9661ae0db10ecdb9bea3ef0c5fb46bb233cb6ed7404b77e7b0732512ecc60101 => 2ce182cf5cb40833cb3f00000000000000000000000000000000000000000000
	9661ae0db10ecdb9bea3ef0c5fb46bb233cb6ed7404b77e7b0732512ecc60102 => 0200000000000000000000000000000000000000000000000000000000000000
	9661ae0db10ecdb9bea3ef0c5fb46bb233cb6ed7404b77e7b0732512ecc60103 => c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470
	9661ae0db10ecdb9bea3ef0c5fb46bb233cb6ed7404b77e7b0732512ecc60104 => 0000000000000000000000000000000000000000000000000000000000000000
proof=Verkle proof:
 * verification hints: 1 1 Present Present 
 * commitments: 538d6beebb32756be0b22c51ae45a9ed96f0299a2fd01f9ef6887946c26fffd2 5ce9c5ef692a444a65a087ce1cb90a59599bd1249c1fd787eb56787949a8f1e8 37a9007019834bef8e2c9e2ae868e33370b5a6723bab8a571d0da40046da856f 6b90812ef10962d894a520a03813da890084b726e7396b585645ace2dc6c00d7 5a1fe87728a033caa1184f1349f1a1e70909d9eef21f470499f62f0ebbe38797 
thread 'main' panicked at 'the proof didn't check', src/main.rs:91:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
i.e. the proof didn't verify. I  now have the same tool written in Go, and the proof checks.

The real bug is that rust fails to verify where even go manages to do it. Unacceptable :angry: 

Picture of the reconstructed tree:
![image](https://user-images.githubusercontent.com/3272758/178254349-5b63ef66-adc1-4f37-8c67-94baafd4dee4.png)

To be fair, for the go code to verify this block, I had to fix an issue, maybe rust-verkle has the same? The issue was caused by `GetProofItems` returning `0` as a `yi` instead of ignoring it because it was not present.

**Comment by kevaundray** [comment]
Can you elaborate on the last part: "returning 0 as a yi instead of ignoring it because it was not present" ?

It may be easier for now to implement the protocol as the python code did, and then apply optimisations after in lock step. It seems that this is the common trait in all issues regarding interopability.

**Comment by gballet** [comment]
meaning it considered that a value that was not present in the initial, was present in the reconstructed tree and set to 0.

**Comment by gballet** [comment]
Thanks to your help I was able to compare the `zis` from both library, the issue is described here: https://github.com/gballet/go-verkle/issues/244 `go-verkle` does not store all of its zis breadth-first. I will fix that.
