### ISSUE TITLE
Why Value type is [u8;32]?

### ISSUE THREAD

**Issue by GrapeBaBa** [crate-crypto/rust-verkle#55]
What is the purpose or limitation for value is only 32 bytes?
```rust
   pub type Value = [u8; 32];

    /// Inserts a single value
    /// This method will implicitly compute the new root
    fn insert_single(&mut self, key: Key, value: Value) {
        self.insert(vec![(key, value)].into_iter())
    }
```

**Comment by kevaundray** [comment]
Great question. This is an ethereum specific limitation noted in https://notes.ethereum.org/@vbuterin/verkle_tree_eip#Tree-embedding

If you have a structure that is more than 32 bytes, you can always hash it with a collision resistant hash function like sha256 to produce 32 bytes

**Comment by GrapeBaBa** [comment]
@kevaundray Thanks. Does it mean we actually not store origin value in verkle trie instead of hash? We need a separate persistent storage to store H(origin value): origin value mapping?

**Comment by GrapeBaBa** [comment]
I just looked at latest go-ethereum code, it seems actually accountState and contractState stored in snapshot tree and but hashes stored in verkle trie.
