### ISSUE TITLE
Why do we need store `hash_commitment`

### ISSUE THREAD

**Issue by GrapeBaBa** [crate-crypto/rust-verkle#58]
```rust
        BranchMeta {
            commitment,
            hash_commitment,
        }
```
Why do we need store `hash_commitment`, can compressed commitment (also 32 bytes) instead of it?

**Comment by kevaundray** [comment]
Hi, 

Great question.

> Why do we need to store the hash_commitment?

Its possible to not store the hash_commitment, but everytime we need it, we will need to compute it from the commitment. Here I was trading off the possible compute time for storage.

> can we use compressed commitment (also 32 bytes) instead of it?

Yeah so this is a good nuanced question. We _could_ also use compressed commitment. However, this way of converting from a commitment to a field is not zero knowledge friendly*. 

We use "compressed commitment" when we want to serialise commitments to be sent over the wire, and we use this "hash_commitment" for when we want to convert a commitment to a field which is 32 bytes, for use in a verkle proof.

*Inverses are cheap in a zero knowledge context so we do mapToField which internally does X/Y.
